// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/hero.proto

package protomsg;

public final class Hero {
  private Hero() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HeroInfoMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 configId = 1;
    boolean hasConfigId();
    int getConfigId();
    
    // required int32 level = 2;
    boolean hasLevel();
    int getLevel();
  }
  public static final class HeroInfoMsg extends
      com.google.protobuf.GeneratedMessage
      implements HeroInfoMsgOrBuilder {
    // Use HeroInfoMsg.newBuilder() to construct.
    private HeroInfoMsg(Builder builder) {
      super(builder);
    }
    private HeroInfoMsg(boolean noInit) {}
    
    private static final HeroInfoMsg defaultInstance;
    public static HeroInfoMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public HeroInfoMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protomsg.Hero.internal_static_HeroInfoMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protomsg.Hero.internal_static_HeroInfoMsg_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 configId = 1;
    public static final int CONFIGID_FIELD_NUMBER = 1;
    private int configId_;
    public boolean hasConfigId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getConfigId() {
      return configId_;
    }
    
    // required int32 level = 2;
    public static final int LEVEL_FIELD_NUMBER = 2;
    private int level_;
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getLevel() {
      return level_;
    }
    
    private void initFields() {
      configId_ = 0;
      level_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasConfigId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, configId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, level_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, configId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, level_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static protomsg.Hero.HeroInfoMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protomsg.Hero.HeroInfoMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protomsg.Hero.HeroInfoMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protomsg.Hero.HeroInfoMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protomsg.Hero.HeroInfoMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protomsg.Hero.HeroInfoMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static protomsg.Hero.HeroInfoMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protomsg.Hero.HeroInfoMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protomsg.Hero.HeroInfoMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protomsg.Hero.HeroInfoMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protomsg.Hero.HeroInfoMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protomsg.Hero.HeroInfoMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protomsg.Hero.internal_static_HeroInfoMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protomsg.Hero.internal_static_HeroInfoMsg_fieldAccessorTable;
      }
      
      // Construct using protomsg.Hero.HeroInfoMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        configId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protomsg.Hero.HeroInfoMsg.getDescriptor();
      }
      
      public protomsg.Hero.HeroInfoMsg getDefaultInstanceForType() {
        return protomsg.Hero.HeroInfoMsg.getDefaultInstance();
      }
      
      public protomsg.Hero.HeroInfoMsg build() {
        protomsg.Hero.HeroInfoMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private protomsg.Hero.HeroInfoMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        protomsg.Hero.HeroInfoMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public protomsg.Hero.HeroInfoMsg buildPartial() {
        protomsg.Hero.HeroInfoMsg result = new protomsg.Hero.HeroInfoMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.configId_ = configId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.level_ = level_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protomsg.Hero.HeroInfoMsg) {
          return mergeFrom((protomsg.Hero.HeroInfoMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(protomsg.Hero.HeroInfoMsg other) {
        if (other == protomsg.Hero.HeroInfoMsg.getDefaultInstance()) return this;
        if (other.hasConfigId()) {
          setConfigId(other.getConfigId());
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasConfigId()) {
          
          return false;
        }
        if (!hasLevel()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              configId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              level_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 configId = 1;
      private int configId_ ;
      public boolean hasConfigId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getConfigId() {
        return configId_;
      }
      public Builder setConfigId(int value) {
        bitField0_ |= 0x00000001;
        configId_ = value;
        onChanged();
        return this;
      }
      public Builder clearConfigId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        configId_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 level = 2;
      private int level_ ;
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getLevel() {
        return level_;
      }
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000002;
        level_ = value;
        onChanged();
        return this;
      }
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        level_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:HeroInfoMsg)
    }
    
    static {
      defaultInstance = new HeroInfoMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:HeroInfoMsg)
  }
  
  public interface HeroInfoListMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .HeroInfoMsg heroList = 1;
    java.util.List<protomsg.Hero.HeroInfoMsg> 
        getHeroListList();
    protomsg.Hero.HeroInfoMsg getHeroList(int index);
    int getHeroListCount();
    java.util.List<? extends protomsg.Hero.HeroInfoMsgOrBuilder> 
        getHeroListOrBuilderList();
    protomsg.Hero.HeroInfoMsgOrBuilder getHeroListOrBuilder(
        int index);
  }
  public static final class HeroInfoListMsg extends
      com.google.protobuf.GeneratedMessage
      implements HeroInfoListMsgOrBuilder {
    // Use HeroInfoListMsg.newBuilder() to construct.
    private HeroInfoListMsg(Builder builder) {
      super(builder);
    }
    private HeroInfoListMsg(boolean noInit) {}
    
    private static final HeroInfoListMsg defaultInstance;
    public static HeroInfoListMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public HeroInfoListMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protomsg.Hero.internal_static_HeroInfoListMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protomsg.Hero.internal_static_HeroInfoListMsg_fieldAccessorTable;
    }
    
    // repeated .HeroInfoMsg heroList = 1;
    public static final int HEROLIST_FIELD_NUMBER = 1;
    private java.util.List<protomsg.Hero.HeroInfoMsg> heroList_;
    public java.util.List<protomsg.Hero.HeroInfoMsg> getHeroListList() {
      return heroList_;
    }
    public java.util.List<? extends protomsg.Hero.HeroInfoMsgOrBuilder> 
        getHeroListOrBuilderList() {
      return heroList_;
    }
    public int getHeroListCount() {
      return heroList_.size();
    }
    public protomsg.Hero.HeroInfoMsg getHeroList(int index) {
      return heroList_.get(index);
    }
    public protomsg.Hero.HeroInfoMsgOrBuilder getHeroListOrBuilder(
        int index) {
      return heroList_.get(index);
    }
    
    private void initFields() {
      heroList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getHeroListCount(); i++) {
        if (!getHeroList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < heroList_.size(); i++) {
        output.writeMessage(1, heroList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < heroList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, heroList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static protomsg.Hero.HeroInfoListMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protomsg.Hero.HeroInfoListMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protomsg.Hero.HeroInfoListMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protomsg.Hero.HeroInfoListMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protomsg.Hero.HeroInfoListMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protomsg.Hero.HeroInfoListMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static protomsg.Hero.HeroInfoListMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protomsg.Hero.HeroInfoListMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protomsg.Hero.HeroInfoListMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protomsg.Hero.HeroInfoListMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protomsg.Hero.HeroInfoListMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protomsg.Hero.HeroInfoListMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protomsg.Hero.internal_static_HeroInfoListMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protomsg.Hero.internal_static_HeroInfoListMsg_fieldAccessorTable;
      }
      
      // Construct using protomsg.Hero.HeroInfoListMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeroListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (heroListBuilder_ == null) {
          heroList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          heroListBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protomsg.Hero.HeroInfoListMsg.getDescriptor();
      }
      
      public protomsg.Hero.HeroInfoListMsg getDefaultInstanceForType() {
        return protomsg.Hero.HeroInfoListMsg.getDefaultInstance();
      }
      
      public protomsg.Hero.HeroInfoListMsg build() {
        protomsg.Hero.HeroInfoListMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private protomsg.Hero.HeroInfoListMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        protomsg.Hero.HeroInfoListMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public protomsg.Hero.HeroInfoListMsg buildPartial() {
        protomsg.Hero.HeroInfoListMsg result = new protomsg.Hero.HeroInfoListMsg(this);
        int from_bitField0_ = bitField0_;
        if (heroListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            heroList_ = java.util.Collections.unmodifiableList(heroList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.heroList_ = heroList_;
        } else {
          result.heroList_ = heroListBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protomsg.Hero.HeroInfoListMsg) {
          return mergeFrom((protomsg.Hero.HeroInfoListMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(protomsg.Hero.HeroInfoListMsg other) {
        if (other == protomsg.Hero.HeroInfoListMsg.getDefaultInstance()) return this;
        if (heroListBuilder_ == null) {
          if (!other.heroList_.isEmpty()) {
            if (heroList_.isEmpty()) {
              heroList_ = other.heroList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureHeroListIsMutable();
              heroList_.addAll(other.heroList_);
            }
            onChanged();
          }
        } else {
          if (!other.heroList_.isEmpty()) {
            if (heroListBuilder_.isEmpty()) {
              heroListBuilder_.dispose();
              heroListBuilder_ = null;
              heroList_ = other.heroList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              heroListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getHeroListFieldBuilder() : null;
            } else {
              heroListBuilder_.addAllMessages(other.heroList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getHeroListCount(); i++) {
          if (!getHeroList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              protomsg.Hero.HeroInfoMsg.Builder subBuilder = protomsg.Hero.HeroInfoMsg.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addHeroList(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .HeroInfoMsg heroList = 1;
      private java.util.List<protomsg.Hero.HeroInfoMsg> heroList_ =
        java.util.Collections.emptyList();
      private void ensureHeroListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          heroList_ = new java.util.ArrayList<protomsg.Hero.HeroInfoMsg>(heroList_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          protomsg.Hero.HeroInfoMsg, protomsg.Hero.HeroInfoMsg.Builder, protomsg.Hero.HeroInfoMsgOrBuilder> heroListBuilder_;
      
      public java.util.List<protomsg.Hero.HeroInfoMsg> getHeroListList() {
        if (heroListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(heroList_);
        } else {
          return heroListBuilder_.getMessageList();
        }
      }
      public int getHeroListCount() {
        if (heroListBuilder_ == null) {
          return heroList_.size();
        } else {
          return heroListBuilder_.getCount();
        }
      }
      public protomsg.Hero.HeroInfoMsg getHeroList(int index) {
        if (heroListBuilder_ == null) {
          return heroList_.get(index);
        } else {
          return heroListBuilder_.getMessage(index);
        }
      }
      public Builder setHeroList(
          int index, protomsg.Hero.HeroInfoMsg value) {
        if (heroListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeroListIsMutable();
          heroList_.set(index, value);
          onChanged();
        } else {
          heroListBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setHeroList(
          int index, protomsg.Hero.HeroInfoMsg.Builder builderForValue) {
        if (heroListBuilder_ == null) {
          ensureHeroListIsMutable();
          heroList_.set(index, builderForValue.build());
          onChanged();
        } else {
          heroListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addHeroList(protomsg.Hero.HeroInfoMsg value) {
        if (heroListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeroListIsMutable();
          heroList_.add(value);
          onChanged();
        } else {
          heroListBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addHeroList(
          int index, protomsg.Hero.HeroInfoMsg value) {
        if (heroListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHeroListIsMutable();
          heroList_.add(index, value);
          onChanged();
        } else {
          heroListBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addHeroList(
          protomsg.Hero.HeroInfoMsg.Builder builderForValue) {
        if (heroListBuilder_ == null) {
          ensureHeroListIsMutable();
          heroList_.add(builderForValue.build());
          onChanged();
        } else {
          heroListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addHeroList(
          int index, protomsg.Hero.HeroInfoMsg.Builder builderForValue) {
        if (heroListBuilder_ == null) {
          ensureHeroListIsMutable();
          heroList_.add(index, builderForValue.build());
          onChanged();
        } else {
          heroListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllHeroList(
          java.lang.Iterable<? extends protomsg.Hero.HeroInfoMsg> values) {
        if (heroListBuilder_ == null) {
          ensureHeroListIsMutable();
          super.addAll(values, heroList_);
          onChanged();
        } else {
          heroListBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearHeroList() {
        if (heroListBuilder_ == null) {
          heroList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          heroListBuilder_.clear();
        }
        return this;
      }
      public Builder removeHeroList(int index) {
        if (heroListBuilder_ == null) {
          ensureHeroListIsMutable();
          heroList_.remove(index);
          onChanged();
        } else {
          heroListBuilder_.remove(index);
        }
        return this;
      }
      public protomsg.Hero.HeroInfoMsg.Builder getHeroListBuilder(
          int index) {
        return getHeroListFieldBuilder().getBuilder(index);
      }
      public protomsg.Hero.HeroInfoMsgOrBuilder getHeroListOrBuilder(
          int index) {
        if (heroListBuilder_ == null) {
          return heroList_.get(index);  } else {
          return heroListBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends protomsg.Hero.HeroInfoMsgOrBuilder> 
           getHeroListOrBuilderList() {
        if (heroListBuilder_ != null) {
          return heroListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(heroList_);
        }
      }
      public protomsg.Hero.HeroInfoMsg.Builder addHeroListBuilder() {
        return getHeroListFieldBuilder().addBuilder(
            protomsg.Hero.HeroInfoMsg.getDefaultInstance());
      }
      public protomsg.Hero.HeroInfoMsg.Builder addHeroListBuilder(
          int index) {
        return getHeroListFieldBuilder().addBuilder(
            index, protomsg.Hero.HeroInfoMsg.getDefaultInstance());
      }
      public java.util.List<protomsg.Hero.HeroInfoMsg.Builder> 
           getHeroListBuilderList() {
        return getHeroListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          protomsg.Hero.HeroInfoMsg, protomsg.Hero.HeroInfoMsg.Builder, protomsg.Hero.HeroInfoMsgOrBuilder> 
          getHeroListFieldBuilder() {
        if (heroListBuilder_ == null) {
          heroListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              protomsg.Hero.HeroInfoMsg, protomsg.Hero.HeroInfoMsg.Builder, protomsg.Hero.HeroInfoMsgOrBuilder>(
                  heroList_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          heroList_ = null;
        }
        return heroListBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:HeroInfoListMsg)
    }
    
    static {
      defaultInstance = new HeroInfoListMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:HeroInfoListMsg)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HeroInfoMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HeroInfoMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HeroInfoListMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HeroInfoListMsg_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021protos/hero.proto\".\n\013HeroInfoMsg\022\020\n\010co" +
      "nfigId\030\001 \002(\005\022\r\n\005level\030\002 \002(\005\"1\n\017HeroInfoL" +
      "istMsg\022\036\n\010heroList\030\001 \003(\0132\014.HeroInfoMsgB\n" +
      "\n\010protomsg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_HeroInfoMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_HeroInfoMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HeroInfoMsg_descriptor,
              new java.lang.String[] { "ConfigId", "Level", },
              protomsg.Hero.HeroInfoMsg.class,
              protomsg.Hero.HeroInfoMsg.Builder.class);
          internal_static_HeroInfoListMsg_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_HeroInfoListMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HeroInfoListMsg_descriptor,
              new java.lang.String[] { "HeroList", },
              protomsg.Hero.HeroInfoListMsg.class,
              protomsg.Hero.HeroInfoListMsg.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
