// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/login.proto

package protomsg;

public final class Login {
  private Login() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LoginMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string accountId = 1;
    boolean hasAccountId();
    String getAccountId();
    
    // required string accountPwd = 2;
    boolean hasAccountPwd();
    String getAccountPwd();
  }
  public static final class LoginMsg extends
      com.google.protobuf.GeneratedMessage
      implements LoginMsgOrBuilder {
    // Use LoginMsg.newBuilder() to construct.
    private LoginMsg(Builder builder) {
      super(builder);
    }
    private LoginMsg(boolean noInit) {}
    
    private static final LoginMsg defaultInstance;
    public static LoginMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public LoginMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protomsg.Login.internal_static_LoginMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protomsg.Login.internal_static_LoginMsg_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string accountId = 1;
    public static final int ACCOUNTID_FIELD_NUMBER = 1;
    private java.lang.Object accountId_;
    public boolean hasAccountId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getAccountId() {
      java.lang.Object ref = accountId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          accountId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAccountIdBytes() {
      java.lang.Object ref = accountId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        accountId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string accountPwd = 2;
    public static final int ACCOUNTPWD_FIELD_NUMBER = 2;
    private java.lang.Object accountPwd_;
    public boolean hasAccountPwd() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getAccountPwd() {
      java.lang.Object ref = accountPwd_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          accountPwd_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAccountPwdBytes() {
      java.lang.Object ref = accountPwd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        accountPwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      accountId_ = "";
      accountPwd_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasAccountId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAccountPwd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAccountIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAccountPwdBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAccountIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAccountPwdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static protomsg.Login.LoginMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protomsg.Login.LoginMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protomsg.Login.LoginMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protomsg.Login.LoginMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protomsg.Login.LoginMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protomsg.Login.LoginMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static protomsg.Login.LoginMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protomsg.Login.LoginMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protomsg.Login.LoginMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protomsg.Login.LoginMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protomsg.Login.LoginMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protomsg.Login.LoginMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protomsg.Login.internal_static_LoginMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protomsg.Login.internal_static_LoginMsg_fieldAccessorTable;
      }
      
      // Construct using protomsg.Login.LoginMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        accountId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        accountPwd_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protomsg.Login.LoginMsg.getDescriptor();
      }
      
      public protomsg.Login.LoginMsg getDefaultInstanceForType() {
        return protomsg.Login.LoginMsg.getDefaultInstance();
      }
      
      public protomsg.Login.LoginMsg build() {
        protomsg.Login.LoginMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private protomsg.Login.LoginMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        protomsg.Login.LoginMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public protomsg.Login.LoginMsg buildPartial() {
        protomsg.Login.LoginMsg result = new protomsg.Login.LoginMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.accountId_ = accountId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.accountPwd_ = accountPwd_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protomsg.Login.LoginMsg) {
          return mergeFrom((protomsg.Login.LoginMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(protomsg.Login.LoginMsg other) {
        if (other == protomsg.Login.LoginMsg.getDefaultInstance()) return this;
        if (other.hasAccountId()) {
          setAccountId(other.getAccountId());
        }
        if (other.hasAccountPwd()) {
          setAccountPwd(other.getAccountPwd());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasAccountId()) {
          
          return false;
        }
        if (!hasAccountPwd()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              accountId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              accountPwd_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string accountId = 1;
      private java.lang.Object accountId_ = "";
      public boolean hasAccountId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getAccountId() {
        java.lang.Object ref = accountId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          accountId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAccountId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        accountId_ = value;
        onChanged();
        return this;
      }
      public Builder clearAccountId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        accountId_ = getDefaultInstance().getAccountId();
        onChanged();
        return this;
      }
      void setAccountId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        accountId_ = value;
        onChanged();
      }
      
      // required string accountPwd = 2;
      private java.lang.Object accountPwd_ = "";
      public boolean hasAccountPwd() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getAccountPwd() {
        java.lang.Object ref = accountPwd_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          accountPwd_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAccountPwd(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        accountPwd_ = value;
        onChanged();
        return this;
      }
      public Builder clearAccountPwd() {
        bitField0_ = (bitField0_ & ~0x00000002);
        accountPwd_ = getDefaultInstance().getAccountPwd();
        onChanged();
        return this;
      }
      void setAccountPwd(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        accountPwd_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:LoginMsg)
    }
    
    static {
      defaultInstance = new LoginMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:LoginMsg)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LoginMsg_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022protos/login.proto\"1\n\010LoginMsg\022\021\n\tacco" +
      "untId\030\001 \002(\t\022\022\n\naccountPwd\030\002 \002(\tB\n\n\010proto" +
      "msg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_LoginMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_LoginMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_LoginMsg_descriptor,
              new java.lang.String[] { "AccountId", "AccountPwd", },
              protomsg.Login.LoginMsg.class,
              protomsg.Login.LoginMsg.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
