// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/player.proto

package protomsg;

public final class Player {
  private Player() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PlayerCreateMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string nickName = 1;
    boolean hasNickName();
    String getNickName();
  }
  public static final class PlayerCreateMsg extends
      com.google.protobuf.GeneratedMessage
      implements PlayerCreateMsgOrBuilder {
    // Use PlayerCreateMsg.newBuilder() to construct.
    private PlayerCreateMsg(Builder builder) {
      super(builder);
    }
    private PlayerCreateMsg(boolean noInit) {}
    
    private static final PlayerCreateMsg defaultInstance;
    public static PlayerCreateMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public PlayerCreateMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protomsg.Player.internal_static_PlayerCreateMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protomsg.Player.internal_static_PlayerCreateMsg_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string nickName = 1;
    public static final int NICKNAME_FIELD_NUMBER = 1;
    private java.lang.Object nickName_;
    public boolean hasNickName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getNickName() {
      java.lang.Object ref = nickName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          nickName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNickNameBytes() {
      java.lang.Object ref = nickName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        nickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      nickName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasNickName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNickNameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNickNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static protomsg.Player.PlayerCreateMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protomsg.Player.PlayerCreateMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protomsg.Player.PlayerCreateMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protomsg.Player.PlayerCreateMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protomsg.Player.PlayerCreateMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protomsg.Player.PlayerCreateMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static protomsg.Player.PlayerCreateMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protomsg.Player.PlayerCreateMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protomsg.Player.PlayerCreateMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protomsg.Player.PlayerCreateMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protomsg.Player.PlayerCreateMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protomsg.Player.PlayerCreateMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protomsg.Player.internal_static_PlayerCreateMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protomsg.Player.internal_static_PlayerCreateMsg_fieldAccessorTable;
      }
      
      // Construct using protomsg.Player.PlayerCreateMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        nickName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protomsg.Player.PlayerCreateMsg.getDescriptor();
      }
      
      public protomsg.Player.PlayerCreateMsg getDefaultInstanceForType() {
        return protomsg.Player.PlayerCreateMsg.getDefaultInstance();
      }
      
      public protomsg.Player.PlayerCreateMsg build() {
        protomsg.Player.PlayerCreateMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private protomsg.Player.PlayerCreateMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        protomsg.Player.PlayerCreateMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public protomsg.Player.PlayerCreateMsg buildPartial() {
        protomsg.Player.PlayerCreateMsg result = new protomsg.Player.PlayerCreateMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nickName_ = nickName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protomsg.Player.PlayerCreateMsg) {
          return mergeFrom((protomsg.Player.PlayerCreateMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(protomsg.Player.PlayerCreateMsg other) {
        if (other == protomsg.Player.PlayerCreateMsg.getDefaultInstance()) return this;
        if (other.hasNickName()) {
          setNickName(other.getNickName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasNickName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              nickName_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string nickName = 1;
      private java.lang.Object nickName_ = "";
      public boolean hasNickName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getNickName() {
        java.lang.Object ref = nickName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          nickName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNickName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        nickName_ = value;
        onChanged();
        return this;
      }
      public Builder clearNickName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nickName_ = getDefaultInstance().getNickName();
        onChanged();
        return this;
      }
      void setNickName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        nickName_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:PlayerCreateMsg)
    }
    
    static {
      defaultInstance = new PlayerCreateMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PlayerCreateMsg)
  }
  
  public interface PlayerInfoMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 pid = 1;
    boolean hasPid();
    int getPid();
    
    // required string nickName = 2;
    boolean hasNickName();
    String getNickName();
    
    // required int32 selectTeamId = 3;
    boolean hasSelectTeamId();
    int getSelectTeamId();
  }
  public static final class PlayerInfoMsg extends
      com.google.protobuf.GeneratedMessage
      implements PlayerInfoMsgOrBuilder {
    // Use PlayerInfoMsg.newBuilder() to construct.
    private PlayerInfoMsg(Builder builder) {
      super(builder);
    }
    private PlayerInfoMsg(boolean noInit) {}
    
    private static final PlayerInfoMsg defaultInstance;
    public static PlayerInfoMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public PlayerInfoMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protomsg.Player.internal_static_PlayerInfoMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protomsg.Player.internal_static_PlayerInfoMsg_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 pid = 1;
    public static final int PID_FIELD_NUMBER = 1;
    private int pid_;
    public boolean hasPid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getPid() {
      return pid_;
    }
    
    // required string nickName = 2;
    public static final int NICKNAME_FIELD_NUMBER = 2;
    private java.lang.Object nickName_;
    public boolean hasNickName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getNickName() {
      java.lang.Object ref = nickName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          nickName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNickNameBytes() {
      java.lang.Object ref = nickName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        nickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 selectTeamId = 3;
    public static final int SELECTTEAMID_FIELD_NUMBER = 3;
    private int selectTeamId_;
    public boolean hasSelectTeamId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getSelectTeamId() {
      return selectTeamId_;
    }
    
    private void initFields() {
      pid_ = 0;
      nickName_ = "";
      selectTeamId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNickName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSelectTeamId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, pid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNickNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, selectTeamId_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, pid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNickNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, selectTeamId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static protomsg.Player.PlayerInfoMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protomsg.Player.PlayerInfoMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protomsg.Player.PlayerInfoMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protomsg.Player.PlayerInfoMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protomsg.Player.PlayerInfoMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protomsg.Player.PlayerInfoMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static protomsg.Player.PlayerInfoMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protomsg.Player.PlayerInfoMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protomsg.Player.PlayerInfoMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protomsg.Player.PlayerInfoMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protomsg.Player.PlayerInfoMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protomsg.Player.PlayerInfoMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protomsg.Player.internal_static_PlayerInfoMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protomsg.Player.internal_static_PlayerInfoMsg_fieldAccessorTable;
      }
      
      // Construct using protomsg.Player.PlayerInfoMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        pid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        nickName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        selectTeamId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protomsg.Player.PlayerInfoMsg.getDescriptor();
      }
      
      public protomsg.Player.PlayerInfoMsg getDefaultInstanceForType() {
        return protomsg.Player.PlayerInfoMsg.getDefaultInstance();
      }
      
      public protomsg.Player.PlayerInfoMsg build() {
        protomsg.Player.PlayerInfoMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private protomsg.Player.PlayerInfoMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        protomsg.Player.PlayerInfoMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public protomsg.Player.PlayerInfoMsg buildPartial() {
        protomsg.Player.PlayerInfoMsg result = new protomsg.Player.PlayerInfoMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pid_ = pid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nickName_ = nickName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.selectTeamId_ = selectTeamId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protomsg.Player.PlayerInfoMsg) {
          return mergeFrom((protomsg.Player.PlayerInfoMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(protomsg.Player.PlayerInfoMsg other) {
        if (other == protomsg.Player.PlayerInfoMsg.getDefaultInstance()) return this;
        if (other.hasPid()) {
          setPid(other.getPid());
        }
        if (other.hasNickName()) {
          setNickName(other.getNickName());
        }
        if (other.hasSelectTeamId()) {
          setSelectTeamId(other.getSelectTeamId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPid()) {
          
          return false;
        }
        if (!hasNickName()) {
          
          return false;
        }
        if (!hasSelectTeamId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              pid_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              nickName_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              selectTeamId_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 pid = 1;
      private int pid_ ;
      public boolean hasPid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getPid() {
        return pid_;
      }
      public Builder setPid(int value) {
        bitField0_ |= 0x00000001;
        pid_ = value;
        onChanged();
        return this;
      }
      public Builder clearPid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pid_ = 0;
        onChanged();
        return this;
      }
      
      // required string nickName = 2;
      private java.lang.Object nickName_ = "";
      public boolean hasNickName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getNickName() {
        java.lang.Object ref = nickName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          nickName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNickName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        nickName_ = value;
        onChanged();
        return this;
      }
      public Builder clearNickName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nickName_ = getDefaultInstance().getNickName();
        onChanged();
        return this;
      }
      void setNickName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        nickName_ = value;
        onChanged();
      }
      
      // required int32 selectTeamId = 3;
      private int selectTeamId_ ;
      public boolean hasSelectTeamId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getSelectTeamId() {
        return selectTeamId_;
      }
      public Builder setSelectTeamId(int value) {
        bitField0_ |= 0x00000004;
        selectTeamId_ = value;
        onChanged();
        return this;
      }
      public Builder clearSelectTeamId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        selectTeamId_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:PlayerInfoMsg)
    }
    
    static {
      defaultInstance = new PlayerInfoMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PlayerInfoMsg)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerCreateMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PlayerCreateMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerInfoMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PlayerInfoMsg_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023protos/player.proto\"#\n\017PlayerCreateMsg" +
      "\022\020\n\010nickName\030\001 \002(\t\"D\n\rPlayerInfoMsg\022\013\n\003p" +
      "id\030\001 \002(\005\022\020\n\010nickName\030\002 \002(\t\022\024\n\014selectTeam" +
      "Id\030\003 \002(\005B\n\n\010protomsg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_PlayerCreateMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_PlayerCreateMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PlayerCreateMsg_descriptor,
              new java.lang.String[] { "NickName", },
              protomsg.Player.PlayerCreateMsg.class,
              protomsg.Player.PlayerCreateMsg.Builder.class);
          internal_static_PlayerInfoMsg_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_PlayerInfoMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PlayerInfoMsg_descriptor,
              new java.lang.String[] { "Pid", "NickName", "SelectTeamId", },
              protomsg.Player.PlayerInfoMsg.class,
              protomsg.Player.PlayerInfoMsg.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
