// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/rpc.proto

package protomsg;

public final class Rpc {
  private Rpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum Request
      implements com.google.protobuf.ProtocolMessageEnum {
    Login(0, 100),
    Create(1, 101),
    MatchFightReq(2, 200),
    RoomLoadReq(3, 201),
    ReplaceCardReq(4, 202),
    UseReq(5, 203),
    OverRoundReq(6, 206),
    CardAssemblyList(7, 300),
    CardHeroList(8, 301),
    CreateCardTeam(9, 302),
    ChangeTeamName(10, 303),
    HeroOnFight(11, 304),
    ResetCardTeam(12, 305),
    HeroDataReq(13, 306),
    HeroListReq(14, 307),
    ChangeArcane(15, 308),
    CardEnterTeamReq(16, 309),
    CardLeaveTeamReq(17, 310),
    HeroDeleteCardReq(18, 311),
    TeamHeroCardListReq(19, 312),
    ChangeTeamHeroNameReq(20, 313),
    CreateCardTeamReq(21, 314),
    TeamListReq(22, 315),
    CreateRankTeamReq(23, 316),
    CopyCardTeam(24, 317),
    ChangeHeroPos(25, 318),
    ;
    
    public static final int Login_VALUE = 100;
    public static final int Create_VALUE = 101;
    public static final int MatchFightReq_VALUE = 200;
    public static final int RoomLoadReq_VALUE = 201;
    public static final int ReplaceCardReq_VALUE = 202;
    public static final int UseReq_VALUE = 203;
    public static final int OverRoundReq_VALUE = 206;
    public static final int CardAssemblyList_VALUE = 300;
    public static final int CardHeroList_VALUE = 301;
    public static final int CreateCardTeam_VALUE = 302;
    public static final int ChangeTeamName_VALUE = 303;
    public static final int HeroOnFight_VALUE = 304;
    public static final int ResetCardTeam_VALUE = 305;
    public static final int HeroDataReq_VALUE = 306;
    public static final int HeroListReq_VALUE = 307;
    public static final int ChangeArcane_VALUE = 308;
    public static final int CardEnterTeamReq_VALUE = 309;
    public static final int CardLeaveTeamReq_VALUE = 310;
    public static final int HeroDeleteCardReq_VALUE = 311;
    public static final int TeamHeroCardListReq_VALUE = 312;
    public static final int ChangeTeamHeroNameReq_VALUE = 313;
    public static final int CreateCardTeamReq_VALUE = 314;
    public static final int TeamListReq_VALUE = 315;
    public static final int CreateRankTeamReq_VALUE = 316;
    public static final int CopyCardTeam_VALUE = 317;
    public static final int ChangeHeroPos_VALUE = 318;
    
    
    public final int getNumber() { return value; }
    
    public static Request valueOf(int value) {
      switch (value) {
        case 100: return Login;
        case 101: return Create;
        case 200: return MatchFightReq;
        case 201: return RoomLoadReq;
        case 202: return ReplaceCardReq;
        case 203: return UseReq;
        case 206: return OverRoundReq;
        case 300: return CardAssemblyList;
        case 301: return CardHeroList;
        case 302: return CreateCardTeam;
        case 303: return ChangeTeamName;
        case 304: return HeroOnFight;
        case 305: return ResetCardTeam;
        case 306: return HeroDataReq;
        case 307: return HeroListReq;
        case 308: return ChangeArcane;
        case 309: return CardEnterTeamReq;
        case 310: return CardLeaveTeamReq;
        case 311: return HeroDeleteCardReq;
        case 312: return TeamHeroCardListReq;
        case 313: return ChangeTeamHeroNameReq;
        case 314: return CreateCardTeamReq;
        case 315: return TeamListReq;
        case 316: return CreateRankTeamReq;
        case 317: return CopyCardTeam;
        case 318: return ChangeHeroPos;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<Request>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Request>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Request>() {
            public Request findValueByNumber(int number) {
              return Request.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protomsg.Rpc.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final Request[] VALUES = {
      Login, Create, MatchFightReq, RoomLoadReq, ReplaceCardReq, UseReq, OverRoundReq, CardAssemblyList, CardHeroList, CreateCardTeam, ChangeTeamName, HeroOnFight, ResetCardTeam, HeroDataReq, HeroListReq, ChangeArcane, CardEnterTeamReq, CardLeaveTeamReq, HeroDeleteCardReq, TeamHeroCardListReq, ChangeTeamHeroNameReq, CreateCardTeamReq, TeamListReq, CreateRankTeamReq, CopyCardTeam, ChangeHeroPos, 
    };
    
    public static Request valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private Request(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:Request)
  }
  
  public enum Respone
      implements com.google.protobuf.ProtocolMessageEnum {
    ServerResult(0, 1),
    PlayerInfo(1, 100),
    HeroTeamInfo(2, 101),
    ChangeName(3, 102),
    CardTeamList(4, 103),
    HeroFightResult(5, 104),
    HeroDataRes(6, 105),
    HeroListRes(7, 106),
    ArcaneChangeSuc(8, 107),
    CardEnterTeamRes(9, 108),
    CardLeaveTeamRes(10, 109),
    DeletSuitCardRes(11, 110),
    CardTeamHeroRes(12, 111),
    TeamHeraoCardListRes(13, 112),
    ChangeTeamHeroNameRes(14, 113),
    TeamListRes(15, 114),
    RoomInfoRes(16, 200),
    RoomLoadRes(17, 201),
    RoomStateRes(18, 202),
    FightCardsRes(19, 203),
    StartRoundRes(20, 204),
    RoomOverRes(21, 206),
    EffectRes(22, 207),
    ;
    
    public static final int ServerResult_VALUE = 1;
    public static final int PlayerInfo_VALUE = 100;
    public static final int HeroTeamInfo_VALUE = 101;
    public static final int ChangeName_VALUE = 102;
    public static final int CardTeamList_VALUE = 103;
    public static final int HeroFightResult_VALUE = 104;
    public static final int HeroDataRes_VALUE = 105;
    public static final int HeroListRes_VALUE = 106;
    public static final int ArcaneChangeSuc_VALUE = 107;
    public static final int CardEnterTeamRes_VALUE = 108;
    public static final int CardLeaveTeamRes_VALUE = 109;
    public static final int DeletSuitCardRes_VALUE = 110;
    public static final int CardTeamHeroRes_VALUE = 111;
    public static final int TeamHeraoCardListRes_VALUE = 112;
    public static final int ChangeTeamHeroNameRes_VALUE = 113;
    public static final int TeamListRes_VALUE = 114;
    public static final int RoomInfoRes_VALUE = 200;
    public static final int RoomLoadRes_VALUE = 201;
    public static final int RoomStateRes_VALUE = 202;
    public static final int FightCardsRes_VALUE = 203;
    public static final int StartRoundRes_VALUE = 204;
    public static final int RoomOverRes_VALUE = 206;
    public static final int EffectRes_VALUE = 207;
    
    
    public final int getNumber() { return value; }
    
    public static Respone valueOf(int value) {
      switch (value) {
        case 1: return ServerResult;
        case 100: return PlayerInfo;
        case 101: return HeroTeamInfo;
        case 102: return ChangeName;
        case 103: return CardTeamList;
        case 104: return HeroFightResult;
        case 105: return HeroDataRes;
        case 106: return HeroListRes;
        case 107: return ArcaneChangeSuc;
        case 108: return CardEnterTeamRes;
        case 109: return CardLeaveTeamRes;
        case 110: return DeletSuitCardRes;
        case 111: return CardTeamHeroRes;
        case 112: return TeamHeraoCardListRes;
        case 113: return ChangeTeamHeroNameRes;
        case 114: return TeamListRes;
        case 200: return RoomInfoRes;
        case 201: return RoomLoadRes;
        case 202: return RoomStateRes;
        case 203: return FightCardsRes;
        case 204: return StartRoundRes;
        case 206: return RoomOverRes;
        case 207: return EffectRes;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<Respone>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Respone>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Respone>() {
            public Respone findValueByNumber(int number) {
              return Respone.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protomsg.Rpc.getDescriptor().getEnumTypes().get(1);
    }
    
    private static final Respone[] VALUES = {
      ServerResult, PlayerInfo, HeroTeamInfo, ChangeName, CardTeamList, HeroFightResult, HeroDataRes, HeroListRes, ArcaneChangeSuc, CardEnterTeamRes, CardLeaveTeamRes, DeletSuitCardRes, CardTeamHeroRes, TeamHeraoCardListRes, ChangeTeamHeroNameRes, TeamListRes, RoomInfoRes, RoomLoadRes, RoomStateRes, FightCardsRes, StartRoundRes, RoomOverRes, EffectRes, 
    };
    
    public static Respone valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private Respone(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:Respone)
  }
  
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020protos/rpc.proto*\221\004\n\007Request\022\t\n\005Login\020" +
      "d\022\n\n\006Create\020e\022\022\n\rMatchFightReq\020\310\001\022\020\n\013Roo" +
      "mLoadReq\020\311\001\022\023\n\016ReplaceCardReq\020\312\001\022\013\n\006UseR" +
      "eq\020\313\001\022\021\n\014OverRoundReq\020\316\001\022\025\n\020CardAssembly" +
      "List\020\254\002\022\021\n\014CardHeroList\020\255\002\022\023\n\016CreateCard" +
      "Team\020\256\002\022\023\n\016ChangeTeamName\020\257\002\022\020\n\013HeroOnFi" +
      "ght\020\260\002\022\022\n\rResetCardTeam\020\261\002\022\020\n\013HeroDataRe" +
      "q\020\262\002\022\020\n\013HeroListReq\020\263\002\022\021\n\014ChangeArcane\020\264" +
      "\002\022\025\n\020CardEnterTeamReq\020\265\002\022\025\n\020CardLeaveTea" +
      "mReq\020\266\002\022\026\n\021HeroDeleteCardReq\020\267\002\022\030\n\023TeamH",
      "eroCardListReq\020\270\002\022\032\n\025ChangeTeamHeroNameR" +
      "eq\020\271\002\022\026\n\021CreateCardTeamReq\020\272\002\022\020\n\013TeamLis" +
      "tReq\020\273\002\022\026\n\021CreateRankTeamReq\020\274\002\022\021\n\014CopyC" +
      "ardTeam\020\275\002\022\022\n\rChangeHeroPos\020\276\002*\311\003\n\007Respo" +
      "ne\022\020\n\014ServerResult\020\001\022\016\n\nPlayerInfo\020d\022\020\n\014" +
      "HeroTeamInfo\020e\022\016\n\nChangeName\020f\022\020\n\014CardTe" +
      "amList\020g\022\023\n\017HeroFightResult\020h\022\017\n\013HeroDat" +
      "aRes\020i\022\017\n\013HeroListRes\020j\022\023\n\017ArcaneChangeS" +
      "uc\020k\022\024\n\020CardEnterTeamRes\020l\022\024\n\020CardLeaveT" +
      "eamRes\020m\022\024\n\020DeletSuitCardRes\020n\022\023\n\017CardTe",
      "amHeroRes\020o\022\030\n\024TeamHeraoCardListRes\020p\022\031\n" +
      "\025ChangeTeamHeroNameRes\020q\022\017\n\013TeamListRes\020" +
      "r\022\020\n\013RoomInfoRes\020\310\001\022\020\n\013RoomLoadRes\020\311\001\022\021\n" +
      "\014RoomStateRes\020\312\001\022\022\n\rFightCardsRes\020\313\001\022\022\n\r" +
      "StartRoundRes\020\314\001\022\020\n\013RoomOverRes\020\316\001\022\016\n\tEf" +
      "fectRes\020\317\001B\n\n\010protomsg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
