//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: cardAssembly.proto
namespace NetProtocal
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CardListMsg")]
  public partial class CardListMsg : global::ProtoBuf.IExtensible
  {
    public CardListMsg() {}
    
    private readonly global::System.Collections.Generic.List<CardTeamInfo> _cardList = new global::System.Collections.Generic.List<CardTeamInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"cardList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CardTeamInfo> cardList
    {
      get { return _cardList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CardTeamInfo")]
  public partial class CardTeamInfo : global::ProtoBuf.IExtensible
  {
    public CardTeamInfo() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroListMsg")]
  public partial class HeroListMsg : global::ProtoBuf.IExtensible
  {
    public HeroListMsg() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _teamName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"teamName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string teamName
    {
      get { return _teamName; }
      set { _teamName = value; }
    }
    private readonly global::System.Collections.Generic.List<HeroInfo> _heroList = new global::System.Collections.Generic.List<HeroInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"heroList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<HeroInfo> heroList
    {
      get { return _heroList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroInfo")]
  public partial class HeroInfo : global::ProtoBuf.IExtensible
  {
    public HeroInfo() {}
    
    private int _heroUUId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"heroUUId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroUUId
    {
      get { return _heroUUId; }
      set { _heroUUId = value; }
    }
    private int _configId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"configId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int configId
    {
      get { return _configId; }
      set { _configId = value; }
    }
    private int _pos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private int _arcaneId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"arcaneId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int arcaneId
    {
      get { return _arcaneId; }
      set { _arcaneId = value; }
    }
    private string _cardTeamName;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"cardTeamName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string cardTeamName
    {
      get { return _cardTeamName; }
      set { _cardTeamName = value; }
    }
    private int _trialTime;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"trialTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int trialTime
    {
      get { return _trialTime; }
      set { _trialTime = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _skillID = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(7, Name=@"skillID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> skillID
    {
      get { return _skillID; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangeTeamHeroNameMsg")]
  public partial class ChangeTeamHeroNameMsg : global::ProtoBuf.IExtensible
  {
    public ChangeTeamHeroNameMsg() {}
    
    private int _teamId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"teamId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int teamId
    {
      get { return _teamId; }
      set { _teamId = value; }
    }
    private int _heroId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroId
    {
      get { return _heroId; }
      set { _heroId = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroOnFightMsg")]
  public partial class HeroOnFightMsg : global::ProtoBuf.IExtensible
  {
    public HeroOnFightMsg() {}
    
    private int _teamId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"teamId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int teamId
    {
      get { return _teamId; }
      set { _teamId = value; }
    }
    private int _heroId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroId
    {
      get { return _heroId; }
      set { _heroId = value; }
    }
    private int _replaceId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"replaceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int replaceId
    {
      get { return _replaceId; }
      set { _replaceId = value; }
    }
    private int _pos;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateCardTeamMsg")]
  public partial class CreateCardTeamMsg : global::ProtoBuf.IExtensible
  {
    public CreateCardTeamMsg() {}
    
    private int _teamId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"teamId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int teamId
    {
      get { return _teamId; }
      set { _teamId = value; }
    }
    private int _heroConfigId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"heroConfigId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroConfigId
    {
      get { return _heroConfigId; }
      set { _heroConfigId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArcaneMsg")]
  public partial class ArcaneMsg : global::ProtoBuf.IExtensible
  {
    public ArcaneMsg() {}
    
    private int _teamUUid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"teamUUid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int teamUUid
    {
      get { return _teamUUid; }
      set { _teamUUid = value; }
    }
    private int _teamHeroUUid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"teamHeroUUid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int teamHeroUUid
    {
      get { return _teamHeroUUid; }
      set { _teamHeroUUid = value; }
    }
    private int _arcaneId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"arcaneId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int arcaneId
    {
      get { return _arcaneId; }
      set { _arcaneId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CardMsg")]
  public partial class CardMsg : global::ProtoBuf.IExtensible
  {
    public CardMsg() {}
    
    private int _teamUUid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"teamUUid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int teamUUid
    {
      get { return _teamUUid; }
      set { _teamUUid = value; }
    }
    private int _teamHeroUUid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"teamHeroUUid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int teamHeroUUid
    {
      get { return _teamHeroUUid; }
      set { _teamHeroUUid = value; }
    }
    private int _oldCardId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"oldCardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int oldCardId
    {
      get { return _oldCardId; }
      set { _oldCardId = value; }
    }
    private int _newCardId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"newCardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int newCardId
    {
      get { return _newCardId; }
      set { _newCardId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CardInfoListMsg")]
  public partial class CardInfoListMsg : global::ProtoBuf.IExtensible
  {
    public CardInfoListMsg() {}
    
    private int _heroConfigId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"heroConfigId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroConfigId
    {
      get { return _heroConfigId; }
      set { _heroConfigId = value; }
    }
    private int _arcaneId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"arcaneId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int arcaneId
    {
      get { return _arcaneId; }
      set { _arcaneId = value; }
    }
    private int _teamId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"teamId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int teamId
    {
      get { return _teamId; }
      set { _teamId = value; }
    }
    private int _heroId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroId
    {
      get { return _heroId; }
      set { _heroId = value; }
    }
    private string _cardName;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"cardName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string cardName
    {
      get { return _cardName; }
      set { _cardName = value; }
    }
    private readonly global::System.Collections.Generic.List<CardDataMsg> _cardList = new global::System.Collections.Generic.List<CardDataMsg>();
    [global::ProtoBuf.ProtoMember(6, Name=@"cardList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CardDataMsg> cardList
    {
      get { return _cardList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CardDataMsg")]
  public partial class CardDataMsg : global::ProtoBuf.IExtensible
  {
    public CardDataMsg() {}
    
    private int _configId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"configId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int configId
    {
      get { return _configId; }
      set { _configId = value; }
    }

    private int _isFight = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"isFight", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int isFight
    {
      get { return _isFight; }
      set { _isFight = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DeleteSuitCardMsg")]
  public partial class DeleteSuitCardMsg : global::ProtoBuf.IExtensible
  {
    public DeleteSuitCardMsg() {}
    
    private int _teamUUid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"teamUUid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int teamUUid
    {
      get { return _teamUUid; }
      set { _teamUUid = value; }
    }

    private int _teamHeroUUid = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"teamHeroUUid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int teamHeroUUid
    {
      get { return _teamHeroUUid; }
      set { _teamHeroUUid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TeamListMsg")]
  public partial class TeamListMsg : global::ProtoBuf.IExtensible
  {
    public TeamListMsg() {}
    
    private readonly global::System.Collections.Generic.List<SelectTeamMsg> _team = new global::System.Collections.Generic.List<SelectTeamMsg>();
    [global::ProtoBuf.ProtoMember(1, Name=@"team", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<SelectTeamMsg> team
    {
      get { return _team; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SelectTeamMsg")]
  public partial class SelectTeamMsg : global::ProtoBuf.IExtensible
  {
    public SelectTeamMsg() {}
    
    private int _teamId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"teamId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int teamId
    {
      get { return _teamId; }
      set { _teamId = value; }
    }
    private string _teamName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"teamName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string teamName
    {
      get { return _teamName; }
      set { _teamName = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _configIdList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"configIdList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> configIdList
    {
      get { return _configIdList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CopyTeamMsg")]
  public partial class CopyTeamMsg : global::ProtoBuf.IExtensible
  {
    public CopyTeamMsg() {}
    
    private int _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _teamId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"teamId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int teamId
    {
      get { return _teamId; }
      set { _teamId = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangeHeroPosMsg")]
  public partial class ChangeHeroPosMsg : global::ProtoBuf.IExtensible
  {
    public ChangeHeroPosMsg() {}
    
    private int _teamId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"teamId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int teamId
    {
      get { return _teamId; }
      set { _teamId = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _heroId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroId
    {
      get { return _heroId; }
      set { _heroId = value; }
    }
    private int _startPos;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"startPos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int startPos
    {
      get { return _startPos; }
      set { _startPos = value; }
    }
    private int _changId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"changId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int changId
    {
      get { return _changId; }
      set { _changId = value; }
    }
    private int _endPos;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"endPos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int endPos
    {
      get { return _endPos; }
      set { _endPos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: hero.proto
namespace NetProtocal
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroInfoMsg")]
  public partial class HeroInfoMsg : global::ProtoBuf.IExtensible
  {
    public HeroInfoMsg() {}
    
    private int _configId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"configId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int configId
    {
      get { return _configId; }
      set { _configId = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroInfoListMsg")]
  public partial class HeroInfoListMsg : global::ProtoBuf.IExtensible
  {
    public HeroInfoListMsg() {}
    
    private readonly global::System.Collections.Generic.List<HeroInfoMsg> _heroList = new global::System.Collections.Generic.List<HeroInfoMsg>();
    [global::ProtoBuf.ProtoMember(1, Name=@"heroList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<HeroInfoMsg> heroList
    {
      get { return _heroList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: login.proto
namespace NetProtocal
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginMsg")]
  public partial class LoginMsg : global::ProtoBuf.IExtensible
  {
    public LoginMsg() {}
    
    private string _accountId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"accountId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string accountId
    {
      get { return _accountId; }
      set { _accountId = value; }
    }
    private string _accountPwd;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"accountPwd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string accountPwd
    {
      get { return _accountPwd; }
      set { _accountPwd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: player.proto
namespace NetProtocal
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerCreateMsg")]
  public partial class PlayerCreateMsg : global::ProtoBuf.IExtensible
  {
    public PlayerCreateMsg() {}
    
    private string _nickName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInfoMsg")]
  public partial class PlayerInfoMsg : global::ProtoBuf.IExtensible
  {
    public PlayerInfoMsg() {}
    
    private int _pid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pid
    {
      get { return _pid; }
      set { _pid = value; }
    }
    private string _nickName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private int _selectTeamId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"selectTeamId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int selectTeamId
    {
      get { return _selectTeamId; }
      set { _selectTeamId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: result.proto
namespace NetProtocal
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerResultMsg")]
  public partial class ServerResultMsg : global::ProtoBuf.IExtensible
  {
    public ServerResultMsg() {}
    
    private ServerResultFlag _flag;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ServerResultFlag flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ParamIntMsg")]
  public partial class ParamIntMsg : global::ProtoBuf.IExtensible
  {
    public ParamIntMsg() {}
    
    private int _intValue;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"intValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int intValue
    {
      get { return _intValue; }
      set { _intValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ParamStrMsg")]
  public partial class ParamStrMsg : global::ProtoBuf.IExtensible
  {
    public ParamStrMsg() {}
    
    private string _strValue;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"strValue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string strValue
    {
      get { return _strValue; }
      set { _strValue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ServerResultFlag")]
    public enum ServerResultFlag
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Yes", Value=0)]
      Yes = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"No", Value=1)]
      No = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Nothing", Value=2)]
      Nothing = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DisConnected", Value=3)]
      DisConnected = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NickNameRepeat", Value=4)]
      NickNameRepeat = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NullUserId", Value=5)]
      NullUserId = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NullPwd", Value=6)]
      NullPwd = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HaveIllegal", Value=7)]
      HaveIllegal = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NoRole", Value=100)]
      NoRole = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TeamNameRepeat", Value=200)]
      TeamNameRepeat = 200,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HeroFightSucc", Value=201)]
      HeroFightSucc = 201,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HeroFightFail", Value=202)]
      HeroFightFail = 202,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResetCardTeamSuc", Value=203)]
      ResetCardTeamSuc = 203,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CardEnterAlready", Value=204)]
      CardEnterAlready = 204,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CardNoEnter", Value=205)]
      CardNoEnter = 205,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CardTeamNameHasIllegality", Value=206)]
      CardTeamNameHasIllegality = 206,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HeroTeamNameHasIllegality", Value=207)]
      HeroTeamNameHasIllegality = 207
    }
  
}
// Generated from: room.proto
namespace NetProtocal
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MatchFightMsg")]
  public partial class MatchFightMsg : global::ProtoBuf.IExtensible
  {
    public MatchFightMsg() {}
    
    private int _selectTeam;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"selectTeam", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int selectTeam
    {
      get { return _selectTeam; }
      set { _selectTeam = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomInfoMsg")]
  public partial class RoomInfoMsg : global::ProtoBuf.IExtensible
  {
    public RoomInfoMsg() {}
    
    private RoleInfoMsg _frole;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"frole", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public RoleInfoMsg frole
    {
      get { return _frole; }
      set { _frole = value; }
    }
    private RoleInfoMsg _srole;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"srole", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public RoleInfoMsg srole
    {
      get { return _srole; }
      set { _srole = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomLoadMsg")]
  public partial class RoomLoadMsg : global::ProtoBuf.IExtensible
  {
    public RoomLoadMsg() {}
    
    private int _load;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"load", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int load
    {
      get { return _load; }
      set { _load = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomStateMsg")]
  public partial class RoomStateMsg : global::ProtoBuf.IExtensible
  {
    public RoomStateMsg() {}
    
    private RoomState _state;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public RoomState state
    {
      get { return _state; }
      set { _state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoleInfoMsg")]
  public partial class RoleInfoMsg : global::ProtoBuf.IExtensible
  {
    public RoleInfoMsg() {}
    
    private int _pid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pid
    {
      get { return _pid; }
      set { _pid = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _arcaneNum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"arcaneNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int arcaneNum
    {
      get { return _arcaneNum; }
      set { _arcaneNum = value; }
    }
    private int _fatigueTime;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"fatigueTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fatigueTime
    {
      get { return _fatigueTime; }
      set { _fatigueTime = value; }
    }
    private FightCardsMsg _cards;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"cards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public FightCardsMsg cards
    {
      get { return _cards; }
      set { _cards = value; }
    }
    private readonly global::System.Collections.Generic.List<FightHeroMsg> _heros = new global::System.Collections.Generic.List<FightHeroMsg>();
    [global::ProtoBuf.ProtoMember(6, Name=@"heros", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FightHeroMsg> heros
    {
      get { return _heros; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FightHeroMsg")]
  public partial class FightHeroMsg : global::ProtoBuf.IExtensible
  {
    public FightHeroMsg() {}
    
    private int _pid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pid
    {
      get { return _pid; }
      set { _pid = value; }
    }
    private int _index;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _heroId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int heroId
    {
      get { return _heroId; }
      set { _heroId = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _maxHp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"maxHp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxHp
    {
      get { return _maxHp; }
      set { _maxHp = value; }
    }
    private int _shield;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"shield", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int shield
    {
      get { return _shield; }
      set { _shield = value; }
    }
    private int _arcane;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"arcane", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int arcane
    {
      get { return _arcane; }
      set { _arcane = value; }
    }
    private int _pos;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private bool _canMove;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"canMove", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool canMove
    {
      get { return _canMove; }
      set { _canMove = value; }
    }
    private bool _canArcane;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"canArcane", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool canArcane
    {
      get { return _canArcane; }
      set { _canArcane = value; }
    }
    private bool _death;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"death", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool death
    {
      get { return _death; }
      set { _death = value; }
    }
    private int _moveNum;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"moveNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int moveNum
    {
      get { return _moveNum; }
      set { _moveNum = value; }
    }
    private int _useArcaneNum;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"useArcaneNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int useArcaneNum
    {
      get { return _useArcaneNum; }
      set { _useArcaneNum = value; }
    }
    private int _actionNum;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"actionNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int actionNum
    {
      get { return _actionNum; }
      set { _actionNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReplaceCardMsg")]
  public partial class ReplaceCardMsg : global::ProtoBuf.IExtensible
  {
    public ReplaceCardMsg() {}
    
    private bool _replace;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"replace", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool replace
    {
      get { return _replace; }
      set { _replace = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UseMsg")]
  public partial class UseMsg : global::ProtoBuf.IExtensible
  {
    public UseMsg() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private UseType _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public UseType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _target;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"target", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int target
    {
      get { return _target; }
      set { _target = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartRoundMsg")]
  public partial class StartRoundMsg : global::ProtoBuf.IExtensible
  {
    public StartRoundMsg() {}
    
    private int _pid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pid
    {
      get { return _pid; }
      set { _pid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FightCardsMsg")]
  public partial class FightCardsMsg : global::ProtoBuf.IExtensible
  {
    public FightCardsMsg() {}
    
    private readonly global::System.Collections.Generic.List<FightCardMsg> _card = new global::System.Collections.Generic.List<FightCardMsg>();
    [global::ProtoBuf.ProtoMember(1, Name=@"card", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FightCardMsg> card
    {
      get { return _card; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FightCardMsg")]
  public partial class FightCardMsg : global::ProtoBuf.IExtensible
  {
    public FightCardMsg() {}
    
    private int _pid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pid
    {
      get { return _pid; }
      set { _pid = value; }
    }
    private int _index;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _cardId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"cardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cardId
    {
      get { return _cardId; }
      set { _cardId = value; }
    }
    private int _exp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EffectsMsg")]
  public partial class EffectsMsg : global::ProtoBuf.IExtensible
  {
    public EffectsMsg() {}
    
    private readonly global::System.Collections.Generic.List<EffectMsg> _effect = new global::System.Collections.Generic.List<EffectMsg>();
    [global::ProtoBuf.ProtoMember(1, Name=@"effect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<EffectMsg> effect
    {
      get { return _effect; }
    }
  

    private UseMsg _use = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"use", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public UseMsg use
    {
      get { return _use; }
      set { _use = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EffectMsg")]
  public partial class EffectMsg : global::ProtoBuf.IExtensible
  {
    public EffectMsg() {}
    
    private Effecter _source;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"source", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Effecter source
    {
      get { return _source; }
      set { _source = value; }
    }
    private Effecter _target;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"target", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Effecter target
    {
      get { return _target; }
      set { _target = value; }
    }
    private int _prop;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"prop", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int prop
    {
      get { return _prop; }
      set { _prop = value; }
    }
    private int _value;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }

    private FightCardMsg _card = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"card", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FightCardMsg card
    {
      get { return _card; }
      set { _card = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Effecter")]
  public partial class Effecter : global::ProtoBuf.IExtensible
  {
    public Effecter() {}
    
    private int _pid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pid
    {
      get { return _pid; }
      set { _pid = value; }
    }
    private TargetType _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public TargetType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _index;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomOverMsg")]
  public partial class RoomOverMsg : global::ProtoBuf.IExtensible
  {
    public RoomOverMsg() {}
    
    private int _winer;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"winer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int winer
    {
      get { return _winer; }
      set { _winer = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"RoomState")]
    public enum RoomState
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Loading", Value=1)]
      Loading = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Replace", Value=2)]
      Replace = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Fight", Value=3)]
      Fight = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Over", Value=4)]
      Over = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"TargetType")]
    public enum TargetType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Hero", Value=1)]
      Hero = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Card", Value=2)]
      Card = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Role", Value=3)]
      Role = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CardHero", Value=4)]
      CardHero = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"RolePropType")]
    public enum RolePropType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ArcaneNum", Value=1)]
      ArcaneNum = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ExtractCard", Value=2)]
      ExtractCard = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateCard", Value=3)]
      CreateCard = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RemoveCard", Value=4)]
      RemoveCard = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Rank", Value=5)]
      Rank = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameOver", Value=6)]
      GameOver = 6
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"HeroPropType")]
    public enum HeroPropType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Damage", Value=1)]
      Damage = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Hp", Value=2)]
      Hp = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Shield", Value=3)]
      Shield = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Move", Value=4)]
      Move = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Death", Value=5)]
      Death = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CanMove", Value=6)]
      CanMove = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CanArcane", Value=7)]
      CanArcane = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MoveNum", Value=8)]
      MoveNum = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UseArcaneNum", Value=9)]
      UseArcaneNum = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ActionNum", Value=10)]
      ActionNum = 10
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CardPropType")]
    public enum CardPropType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Exp", Value=1)]
      Exp = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Monomer", Value=2)]
      Monomer = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AOE", Value=3)]
      AOE = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"UseType")]
    public enum UseType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CardType", Value=1)]
      CardType = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ExpType", Value=2)]
      ExpType = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MoveType", Value=3)]
      MoveType = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ArcaneType", Value=4)]
      ArcaneType = 4
    }
  
}
// Generated from: rpc.proto
namespace NetProtocal
{
    [global::ProtoBuf.ProtoContract(Name=@"Request")]
    public enum Request
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Login", Value=100)]
      Login = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Create", Value=101)]
      Create = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MatchFightReq", Value=200)]
      MatchFightReq = 200,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RoomLoadReq", Value=201)]
      RoomLoadReq = 201,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReplaceCardReq", Value=202)]
      ReplaceCardReq = 202,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UseReq", Value=203)]
      UseReq = 203,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OverRoundReq", Value=206)]
      OverRoundReq = 206,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CardAssemblyList", Value=300)]
      CardAssemblyList = 300,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CardHeroList", Value=301)]
      CardHeroList = 301,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateCardTeam", Value=302)]
      CreateCardTeam = 302,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChangeTeamName", Value=303)]
      ChangeTeamName = 303,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HeroOnFight", Value=304)]
      HeroOnFight = 304,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ResetCardTeam", Value=305)]
      ResetCardTeam = 305,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HeroDataReq", Value=306)]
      HeroDataReq = 306,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HeroListReq", Value=307)]
      HeroListReq = 307,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChangeArcane", Value=308)]
      ChangeArcane = 308,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CardEnterTeamReq", Value=309)]
      CardEnterTeamReq = 309,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CardLeaveTeamReq", Value=310)]
      CardLeaveTeamReq = 310,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HeroDeleteCardReq", Value=311)]
      HeroDeleteCardReq = 311,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TeamHeroCardListReq", Value=312)]
      TeamHeroCardListReq = 312,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChangeTeamHeroNameReq", Value=313)]
      ChangeTeamHeroNameReq = 313,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateCardTeamReq", Value=314)]
      CreateCardTeamReq = 314,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TeamListReq", Value=315)]
      TeamListReq = 315,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateRankTeamReq", Value=316)]
      CreateRankTeamReq = 316,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CopyCardTeam", Value=317)]
      CopyCardTeam = 317,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChangeHeroPos", Value=318)]
      ChangeHeroPos = 318
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Respone")]
    public enum Respone
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServerResult", Value=1)]
      ServerResult = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerInfo", Value=100)]
      PlayerInfo = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HeroTeamInfo", Value=101)]
      HeroTeamInfo = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChangeName", Value=102)]
      ChangeName = 102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CardTeamList", Value=103)]
      CardTeamList = 103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HeroFightResult", Value=104)]
      HeroFightResult = 104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HeroDataRes", Value=105)]
      HeroDataRes = 105,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HeroListRes", Value=106)]
      HeroListRes = 106,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ArcaneChangeSuc", Value=107)]
      ArcaneChangeSuc = 107,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CardEnterTeamRes", Value=108)]
      CardEnterTeamRes = 108,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CardLeaveTeamRes", Value=109)]
      CardLeaveTeamRes = 109,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DeletSuitCardRes", Value=110)]
      DeletSuitCardRes = 110,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CardTeamHeroRes", Value=111)]
      CardTeamHeroRes = 111,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TeamHeraoCardListRes", Value=112)]
      TeamHeraoCardListRes = 112,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChangeTeamHeroNameRes", Value=113)]
      ChangeTeamHeroNameRes = 113,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TeamListRes", Value=114)]
      TeamListRes = 114,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RoomInfoRes", Value=200)]
      RoomInfoRes = 200,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RoomLoadRes", Value=201)]
      RoomLoadRes = 201,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RoomStateRes", Value=202)]
      RoomStateRes = 202,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FightCardsRes", Value=203)]
      FightCardsRes = 203,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StartRoundRes", Value=204)]
      StartRoundRes = 204,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EffectRes", Value=207)]
      EffectRes = 207
    }
  
}